ACTIVITY_ICONS = {
    "Arts and Culture":"fa-solid fa-masks-theater",
    "Astronomy":"fa-regular fa-star",
    "Auto and ATV":"fa-solid fa-truck-monster",
    "Biking":"fa-solid fa-bicycle",
    "Boating":"fa-solid fa-sailboat",
    "Camping":"fa-solid fa-campground",
    "Canyoneering":"fa-solid fa-mound",
    "Caving":"fa-solid fa-icicles",
    "Climbing":"fa-solid fa-mountain",
    "Compass and GPS":"fa-regular fa-compass",
    "Dog Sledding":"fa-solid fa-dog",
    "Default": "fa-brands fa-envira",
    "Fishing":"fa-solid fa-fish",
    "Flying":"fa-solid fa-plane-departure",
    "Food":"fa-solid fa-utensils",
    "Golfing":"fa-solid fa-golf-ball-tee",
    "Guided Tours":"fa-solid fa-hand-holding",
    "Hands-On":"fa-solid fa-hand",
    "Hiking":"fa-solid fa-person-hiking",
    "Horse Trekking":"fa-solid fa-horse",
    "Hunting and Gathering":"fa-solid fa-feather",
    "Ice Skating":"fa-solid fa-person-skating",
    "Junior Ranger Program":"fa-brands fa-redhat",
    "Living History":"fa-solid fa-tower-observation",
    "Museum Exhibits":"fa-solid fa-landmark",
    "Paddling":"fa-solid fa-anchor",
    "Park Film":"fa-solid fa-film",
    "Playground":"fa-solid fa-children",
    "SCUBA Diving":"fa-solid fa-water-ladder",
    "Shopping":"fa-solid fa-basket-shopping",
    "Skiing":"fa-solid fa-sleigh",
    "Snorkeling":"fa-solid fa-mask",
    "Snow Play":"fa-solid fa-snowman",
    "Snowmobiling":"fa-solid fa-sleigh",
    "Snowshoeing":"fa-solid fa-shoe-prints",
    "Surfing":"fa-solid fa-person-snowboarding",
    "Swimming":"fa-solid fa-person-swimming",
    "Team Sports":"fa-solid fa-people-group",
    "Tubing":"fa-solid fa-bridge-water",
    "Water Skiing":"fa-solid fa-water",
    "Wildlife Watching": "fa-solid fa-binoculars"
}